import 'comic.dart';

final List<Comic> comics = [
  Comic(
    title: 'Spider-Man: Blue',
    author: 'Jeph Loeb',
    price: 14.99,
    imageUrl: 'https://i.pinimg.com/736x/1d/a4/3d/1da43d8742b591be0dd6557410e701b7.jpg',
    category: 'Spider-Man',
    description: 'Это трогательная история о Питере Паркере и Гвен Стейси.',
    quantity: 5,
    isFavorite: false,
    isInCart: false,
  ),
  Comic(
    title: 'Spider-Man: Kraven\'s Last Hunt',
    author: 'J.M. DeMatteis',
    price: 17.99,
    imageUrl: 'https://cdn1.ozone.ru/s3/multimedia-1-d/6933150625.jpg',
    category: 'Spider-Man',
    description: 'Последняя охота Кравена на Человека-паука.',
    quantity: 3,
    isFavorite: false,
    isInCart: false,
  ),
  Comic(
    title: 'Batman: Year One',
    author: 'Frank Miller',
    price: 19.99,
    imageUrl: 'https://s3.amazonaws.com/www.covernk.com/Covers/L/B/Batman+Year+One/batmanyearonetradepaperback1.jpg',
    category: 'Batman',
    description: 'Происхождение Бэтмена.',
    quantity: 7,
    isFavorite: false,
    isInCart: false,
  ),
  Comic(
    title: 'Batman: The Long Halloween',
    author: 'Jeph Loeb',
    price: 22.99,
    imageUrl: 'https://static.tvtropes.org/pmwiki/pub/images/batman_long_halloween_cover.jpg',
    category: 'Batman',
    description: 'Годовая тайна для Бэтмена.',
    quantity: 4,
    isFavorite: false,
    isInCart: false,
  ),
  Comic(
    title: 'Teenage Mutant Ninja Turtles: City at War',
    author: 'Kevin Eastman',
    price: 15.99,
    imageUrl: 'https://vignette.wikia.nocookie.net/tmnt/images/b/b0/Idw91.jpg/revision/latest?cb=20190214074102',
    category: 'Ninja Turtles',
    description: 'Черепашки сталкиваются с городской войной.',
    quantity: 6,
    isFavorite: false,
    isInCart: false,
  ),
  Comic(
    title: 'Teenage Mutant Ninja Turtles: The Last Ronin',
    author: 'Kevin Eastman',
    price: 24.99,
    imageUrl: 'https://i.dailymail.co.uk/1s/2024/04/11/21/83526179-13298943-image-a-142_1712867277901.jpg',
    category: 'Ninja Turtles',
    description: 'Последний выживший Черепашка ищет мести.',
    quantity: 2,
    isFavorite: false,
    isInCart: false,
  ),
];